language: r
cache: packages
warnings_are_errors: false
dist: trusty
notifications:
    on_success: never
    on_failure: true
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
